<a href="https://colab.research.google.com/github/sarahchaewon/DSRP_/blob/main/test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import pandas as pd

In [21]:
url = 'https://raw.githubusercontent.com/frontiertechinstitute/datasets/refs/heads/main/AI%20and%20Digital%20Media/Global_AI_Content_Impact_Dataset.csv'

df = pd.read_csv(url)
df.head()

,Country,Year,Industry,AI Adoption Rate (%),AI-Generated Content Volume (TBs per year),Job Loss Due to AI (%),Revenue Increase Due to AI (%),Human-AI Collaboration Rate (%),Top AI Tools Used,Regulation Status,Consumer Trust in AI (%),Market Share of AI Companies (%)
0,South Korea,2022,Media,44.29,33.09,16.77,46.12,74.79,Bard,Strict,40.77,18.73
1,China,2025,Legal,34.75,66.74,46.89,52.46,26.17,DALL-E,Strict,35.67,35.02
2,USA,2022,Automotive,81.06,96.13,10.66,45.60,39.66,Stable Diffusion,Moderate,54.47,22.76
3,France,2021,Legal,85.24,93.76,27.70,78.24,29.45,Claude,Moderate,51.84,1.93
4,France,2021,Gaming,78.95,45.62,17.45,1.05,21.70,Midjourney,Strict,41.77,21.41

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 12 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Country                                     200 non-null    object
 1   Year                                        200 non-null    int64
 2   Industry                                    200 non-null    object
 3   AI Adoption Rate (%)                        200 non-null    float64
 4   AI-Generated Content Volume (TBs per year)  200 non-null    float64
 5   Job Loss Due to AI (%)                      200 non-null    float64
 6   Revenue Increase Due to AI (%)              200 non-null    float64
 7   Human-AI Collaboration Rate (%)             200 non-null    float64
 8   Top AI Tools Used                           200 non-null    object
 9   Regulation Status                           200 non-null    object
 10  Consumer Trust in AI (%)                    200 non-null    float64
 11  Market Share of AI Companies (%)            200 non-null    float64
dtypes: float64(7), int64(1), object(4)
memory usage: 18.9+ KB

In [23]:
# count how many duplicates are in the dataset / drop duplicates
df.duplicated().sum()
df = df.drop_duplicates()
print(df.duplicated().sum())

0

In [24]:
# count how many missing values are in the dataset : none
df.isna().sum()

Country                                       0
Year                                          0
Industry                                      0
AI Adoption Rate (%)                          0
AI-Generated Content Volume (TBs per year)    0
Job Loss Due to AI (%)                        0
Revenue Increase Due to AI (%)                0
Human-AI Collaboration Rate (%)               0
Top AI Tools Used                             0
Regulation Status                             0
Consumer Trust in AI (%)                      0
Market Share of AI Companies (%)              0
dtype: int64

In [26]:
df.dtypes

Country                                        object
Year                                            int64
Industry                                       object
AI Adoption Rate (%)                          float64
AI-Generated Content Volume (TBs per year)    float64
Job Loss Due to AI (%)                        float64
Revenue Increase Due to AI (%)                float64
Human-AI Collaboration Rate (%)               float64
Top AI Tools Used                              object
Regulation Status                              object
Consumer Trust in AI (%)                      float64
Market Share of AI Companies (%)              float64
dtype: object

In [32]:
# Remove spaces
df['Country'] = df['Country'].str.strip()
print(df['Country'].unique())

['South Korea' 'China' 'USA' 'France' 'Australia' 'UK' 'Canada' 'India'
 'Japan' 'Germany']

In [34]:
# Check if values are outside 0-100
out_of_range = df[
    (df['AI Adoption Rate (%)'] < 0) |
    (df['AI Adoption Rate (%)'] > 100)
]
print('AI Adoption Rate (%):', len(out_of_range))

out_of_range = df[
    (df['Job Loss Due to AI (%)'] < 0) |
    (df['Job Loss Due to AI (%)'] > 100)
]
print('Job Loss Due to AI (%):', len(out_of_range))

out_of_range = df[
    (df['Revenue Increase Due to AI (%)'] < 0) |
    (df['Revenue Increase Due to AI (%)'] > 100)
]
print('Revenue Increase Due to AI (%):', len(out_of_range))

out_of_range = df[
    (df['Human-AI Collaboration Rate (%)'] < 0) |
    (df['Human-AI Collaboration Rate (%)'] > 100)
]
print('Human-AI Collaboration Rate (%):', len(out_of_range))

out_of_range = df[
    (df['Consumer Trust in AI (%)'] < 0) |
    (df['Consumer Trust in AI (%)'] > 100)
]
print('Consumer Trust in AI (%):', len(out_of_range))

out_of_range = df[
    (df['Market Share of AI Companies (%)'] < 0) |
    (df['Market Share of AI Companies (%)'] > 100)
]
print('Market Share of AI Companies (%):', len(out_of_range))

AI Adoption Rate (%): 0
Job Loss Due to AI (%): 0
Revenue Increase Due to AI (%): 0
Human-AI Collaboration Rate (%): 0
Consumer Trust in AI (%): 0
Market Share of AI Companies (%): 0

In [29]:
# check Year values are reasonable
print(df['Year'].min(), df['Year'].max())

2020 2025