<a href="https://colab.research.google.com/github/sarahchaewon/DSRP_/blob/main/test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
url = 'https://raw.githubusercontent.com/sarahchaewon/DSRP_/refs/heads/main/sampled_passwords.csv'

df = pd.read_csv(url)
df.head()

                        Password  Strength_Level
0                   abrocomeLlll               1
1       EZ&c%{(1~;eu7a/uUGL&B}%Z               4
2  ]|VWl>90|3\]dL~_y*fOQa$5Q~?2q               4
3                   accordancyy]               2
4                          xjemt               0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500112 entries, 0 to 1500111
Data columns (total 2 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   Password        1500112 non-null  object
 1   Strength_Level  1500112 non-null  int64
dtypes: int64(1), object(1)
memory usage: 22.9+ MB

In [ ]:
# count how many duplicates are in the dataset / drop duplicates
df.duplicated().sum()
df = df.drop_duplicates()
print(df.duplicated().sum())

np.int64(0)

In [ ]:
# count how many missing values are in the dataset : none
df.isna().sum()

Password          0
Strength_Level    0
dtype: int64

In [ ]:
# check for empty passwords
df['Password'].isnull().sum()

np.int64(0)